#!/bin/sh

if [ $# -lt 2 ]
then
    echo "Usage: $0 path destination"
    exit 1
fi

WATCH_PATH="$1"
shift
DEST=("$@")
rsync_opts=( $RSYNC_OPTS )

notifyloop "$WATCH_PATH" rsync -avz "${rsync_opts[@]}" "$WATCH_PATH" "${DEST[@]}"