.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "NOTIFYWAIT" "1" "January 2014" "" ""
.
.SH "NAME"
\fBnotifywait\fR \- Wait for a file or directory to change\.
.
.SH "SYNOPSIS"
\fBnotifywait\fR [\fIoptions\fR] PATH [PATH] [PATH] [PATH] \.\.\.
.
.SH "DESCRIPTION"
Monitors PATHS for changes\. Paths can be files or directories\.
.
.SH "OPTIONS"
None\.
.
.SH "CAVEATS"
If path is a directory, it must exist when the \fBnotifywait\fR is started\. If path is a file, its parent directory must exist at start time\. This is due to a limitation in FSEvents\.
